// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Orders.proto

package services

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type OrderRequest struct {
	OrderMain            *OrderMain `protobuf:"bytes,1,opt,name=order_main,json=orderMain,proto3" json:"order_main,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *OrderRequest) Reset()         { *m = OrderRequest{} }
func (m *OrderRequest) String() string { return proto.CompactTextString(m) }
func (*OrderRequest) ProtoMessage()    {}
func (*OrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e258ede2b56f8bf, []int{0}
}

func (m *OrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderRequest.Unmarshal(m, b)
}
func (m *OrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderRequest.Marshal(b, m, deterministic)
}
func (m *OrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderRequest.Merge(m, src)
}
func (m *OrderRequest) XXX_Size() int {
	return xxx_messageInfo_OrderRequest.Size(m)
}
func (m *OrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OrderRequest proto.InternalMessageInfo

func (m *OrderRequest) GetOrderMain() *OrderMain {
	if m != nil {
		return m.OrderMain
	}
	return nil
}

type OrderResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderResponse) Reset()         { *m = OrderResponse{} }
func (m *OrderResponse) String() string { return proto.CompactTextString(m) }
func (*OrderResponse) ProtoMessage()    {}
func (*OrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e258ede2b56f8bf, []int{1}
}

func (m *OrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderResponse.Unmarshal(m, b)
}
func (m *OrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderResponse.Marshal(b, m, deterministic)
}
func (m *OrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderResponse.Merge(m, src)
}
func (m *OrderResponse) XXX_Size() int {
	return xxx_messageInfo_OrderResponse.Size(m)
}
func (m *OrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OrderResponse proto.InternalMessageInfo

func (m *OrderResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *OrderResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*OrderRequest)(nil), "services.OrderRequest")
	proto.RegisterType((*OrderResponse)(nil), "services.OrderResponse")
}

func init() { proto.RegisterFile("Orders.proto", fileDescriptor_6e258ede2b56f8bf) }

var fileDescriptor_6e258ede2b56f8bf = []byte{
	// 231 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x8f, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0xd9, 0x3d, 0xac, 0xbb, 0xe3, 0x7a, 0x89, 0xb0, 0x86, 0x22, 0x22, 0x39, 0x79, 0x6a,
	0xb0, 0xde, 0xbc, 0xe9, 0xbd, 0x0a, 0xf5, 0xe8, 0x41, 0x62, 0x3b, 0x94, 0x60, 0x9b, 0xa9, 0x99,
	0xb4, 0xde, 0x7d, 0x05, 0x1f, 0xcd, 0x57, 0xf0, 0x41, 0xc4, 0x98, 0x82, 0xb8, 0xb7, 0x7c, 0x93,
	0xe1, 0x9b, 0xff, 0x87, 0xed, 0xbd, 0x6f, 0xd0, 0x73, 0x3e, 0x78, 0x0a, 0x24, 0xd6, 0x8c, 0x7e,
	0xb2, 0x35, 0x72, 0x76, 0xda, 0x12, 0xb5, 0x1d, 0x6a, 0x33, 0x58, 0x6d, 0x9c, 0xa3, 0x60, 0x82,
	0x25, 0x97, 0xf6, 0xb2, 0x6d, 0x49, 0x0d, 0x76, 0x89, 0xd4, 0x6d, 0xb2, 0x54, 0xf8, 0x3a, 0x22,
	0x07, 0x51, 0x00, 0xd0, 0x0f, 0x3f, 0xf5, 0xc6, 0x3a, 0xb9, 0x38, 0x5f, 0x5c, 0x1c, 0x16, 0xc7,
	0xf9, 0xac, 0xce, 0xe3, 0x6e, 0x69, 0xac, 0xab, 0x36, 0x34, 0x3f, 0xd5, 0x0d, 0x1c, 0x25, 0x07,
	0x0f, 0xe4, 0x18, 0xc5, 0x0e, 0x56, 0x1c, 0x4c, 0x18, 0x39, 0x0a, 0x36, 0x55, 0x22, 0x21, 0xe1,
	0xa0, 0x47, 0x66, 0xd3, 0xa2, 0x5c, 0xc6, 0x8f, 0x19, 0x8b, 0x97, 0x14, 0xe3, 0x01, 0xbd, 0x9d,
	0x6a, 0x14, 0x8f, 0xb0, 0xbe, 0xc3, 0xb7, 0x38, 0x12, 0xbb, 0x7f, 0xe7, 0x53, 0xd4, 0xec, 0x64,
	0x6f, 0xfe, 0x7b, 0x5e, 0x9d, 0xbd, 0x7f, 0x7e, 0x7d, 0x2c, 0xa5, 0x02, 0x3d, 0x5d, 0xea, 0x18,
	0x93, 0xaf, 0xff, 0xb4, 0x7a, 0x5e, 0xc5, 0xea, 0x57, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x42,
	0xc9, 0x5b, 0x16, 0x40, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OrderSerivceClient is the client API for OrderSerivce service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OrderSerivceClient interface {
	NewOrder(ctx context.Context, in *OrderRequest, opts ...grpc.CallOption) (*OrderResponse, error)
}

type orderSerivceClient struct {
	cc *grpc.ClientConn
}

func NewOrderSerivceClient(cc *grpc.ClientConn) OrderSerivceClient {
	return &orderSerivceClient{cc}
}

func (c *orderSerivceClient) NewOrder(ctx context.Context, in *OrderRequest, opts ...grpc.CallOption) (*OrderResponse, error) {
	out := new(OrderResponse)
	err := c.cc.Invoke(ctx, "/services.OrderSerivce/NewOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderSerivceServer is the server API for OrderSerivce service.
type OrderSerivceServer interface {
	NewOrder(context.Context, *OrderRequest) (*OrderResponse, error)
}

// UnimplementedOrderSerivceServer can be embedded to have forward compatible implementations.
type UnimplementedOrderSerivceServer struct {
}

func (*UnimplementedOrderSerivceServer) NewOrder(ctx context.Context, req *OrderRequest) (*OrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewOrder not implemented")
}

func RegisterOrderSerivceServer(s *grpc.Server, srv OrderSerivceServer) {
	s.RegisterService(&_OrderSerivce_serviceDesc, srv)
}

func _OrderSerivce_NewOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderSerivceServer).NewOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.OrderSerivce/NewOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderSerivceServer).NewOrder(ctx, req.(*OrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _OrderSerivce_serviceDesc = grpc.ServiceDesc{
	ServiceName: "services.OrderSerivce",
	HandlerType: (*OrderSerivceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewOrder",
			Handler:    _OrderSerivce_NewOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Orders.proto",
}
